config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products
  resources :baskets
  resources :basket_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  token      :string
#

class Basket < ApplicationRecord
  has_many :basket_items

  has_secure_token

  def total_without_vat
    self.basket_items.map(&:total).sum
  end

  def total_with_vat
    self.basket_items.map(&:final_price).sum
  end

  def total_after_discount
    (total_with_vat - discount_amount).round(2)
  end

  private

  def discount_amount
    (total_with_vat * Deal.overall_discount(self.total_with_vat)) / 100
  end
end

app/models/basket_item.rb
# == Schema Information
#
# Table name: basket_items
#
#  id          :integer          not null, primary key
#  basket_id   :integer
#  quantity    :integer
#  price       :decimal(, )
#  vat_rate_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  product_id  :integer
#

class BasketItem < ApplicationRecord
  belongs_to :product
  belongs_to :basket
  belongs_to :vat_rate

  def total
    (self.quantity * self.price) - Deal.discount(self)
  end

  def final_price
    self.total + (self.total * self.vat_rate.rate) / 100
  end

end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id              :integer          not null, primary key
#  overall         :decimal(, )
#  discount_rate   :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  deal_type       :string
#  quantity        :integer
#  discount_amount :decimal(, )
#

class Deal < ApplicationRecord

  def self.discount(item)
    discount = 0.0
    product = item.product
    if qualifies?(item, product)
      discount += calculate_discount(item, product)
    end

    return discount
  end

  def self.overall_discount(total)
    # replace equal operator with == in order to work on sqlite
    discount = Deal.where(["deal_type = 'total' AND overall <= ?", total]).first
    return discount.discount_rate if !discount.nil?
    return 0.0
  end

  private

  def self.calculate_discount(item, product)
    (item.quantity / product.deal.quantity) * product.deal.discount_amount
  end

  def self.qualifies?(item, product)
    return false if !defined?(product.deal)
    return true if !product.deal.nil? && item.quantity >= product.deal.quantity
  end


end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  price       :decimal(, )
#  vat_rate_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  deal_id     :integer
#

class Product < ApplicationRecord
  belongs_to :vat_rate
  belongs_to :deal
end

app/models/vat_rate.rb
# == Schema Information
#
# Table name: vat_rates
#
#  id         :integer          not null, primary key
#  name       :string
#  rate       :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class VatRate < ApplicationRecord
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_basket
    return @current_basket if defined?(@current_basket)
    session_basket
  end

  private

  def session_basket
    if cookies['basket_token'] && !Basket.find_by_token(cookies['basket_token']).nil?
      current_basket = Basket.find_by_token(cookies['basket_token'])
    else
      current_basket = Basket.create
      cookies['basket_token'] = current_basket.token
    end
    current_basket
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController

  def create
    product = Product.find(basket_item_params[:product_id])

    if current_basket.basket_items.find_by_product_id(product.id).nil?
      basket_item = current_basket.basket_items.build(basket_item_params)
      basket_item.price = product.price
      basket_item.vat_rate_id = product.vat_rate_id
    else
      basket_item = current_basket.basket_items.find_by_product_id(product.id)
      basket_item.quantity += basket_item_params[:quantity].to_i
    end

    if basket_item.save
      redirect_to basket_path(current_basket.id)
    else
      redirect_to products_path
    end
  end

  private

  def basket_item_params
    params.require(:basket_item).permit(:quantity, :product_id)
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  def show
    @current_basket = current_basket
  end

  def update
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @current_basket = current_basket
    @products = Product.all
  end

  def show
    @current_basket = current_basket
    @product = Product.find(params[:id])
    @basket_item = BasketItem.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/baskets/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @current_basket.basket_items.each do |basket_item| %>
      <tr>
        <td><%= basket_item.product.name %></td>
        <td><%= basket_item.product.price %></td>
        <td><%= basket_item.quantity %></td>
        <td><%= basket_item.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>


Total without VAT: <%= @current_basket.total_without_vat%>
<br />
Total with VAT: <%= @current_basket.total_after_discount %> (Any discounts have been deducted)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Shop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Online Shop", products_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Products",   products_path %></li>
            <% if defined? @current_basket %>
              <li><%= link_to "Basket",   basket_path(@current_basket.id) %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'View', product_path(product.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/show.html.erb
Product: <%= @product.name %>
<br>
Price: <%= @product.price %>

<%= form_for @basket_item do |f| %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <%= f.submit "Add to basket" %>
<% end %>